### PR TITLE
Add CSD / Windows Controls

### LINKED ISSUE #14: Window controls
Hey, love your work.

 I usually don't use the title bar, so it will be nice if I can get it back when I'm using this customization [like the way flyingfox had implemented this] how does one go about doing this?

### PR DESCRIPTION
**Pull request by Mr-nUUb**
fixes #14

### CODE REVIEW

**Comment by drannex42** [comment]
I merged this into a new branch, I am making some changes later today that will help across the board for additional customizations. This is really great work.

**Comment by drannex42** [comment]
@Mr-nUUb Could you follow the new instructions in the readme on the 'extensions' branch and see if it works for you?

I broke the extension into components (each component has their own file), I added a prefs.css file, and I made it so you can anable/disable tweaks and change settings. I am not having any issues on my side, but I hope that it works the same on yours. 

https://github.com/drannex42/FirefoxSidebar/tree/extensions

**Comment by drannex42** [comment]
I just merged it with the main branch (on accident, but I'll let it stand for the moment).

**Comment by Xanaxus** [comment]
The line no 261 should be changed to `150px` IMO as it render like this with `95px`:
image
Which is not good according to me

And the line 269 also needs some changes as u can see the window control buttons are not in line with the home button/ prev, pg button, I have kept mine at 10px. Which I guess is due to my custom theme, so I guess a comment will be necessary so that the future users know that this the line which needs to be changed in order to achieve a same plane placement.

**Comment by drannex42** [comment]
Are you using his PR, or the changes I have made to this and implemented in the new version of the Repo?

**Comment by Xanaxus** [comment]
The PR i guess; I just saw the changes in the file changed tab

**Comment by Xanaxus** [comment]
The pref.css file for the side needs a small change on line 23;
`--csd-margin-left: 92px;` to `--csd-margin-left: 140px;`
And the window_contro.css line 25 needs a comment stating that `This line handels the position of the window control button on the vertical plane` as I needed it for my custom de theme

**Comment by drannex42** [comment]
That's the beauty of the prefs.css file, the ability to easily change what each system and user needs (140px is far too much for me, but obviously not for you!)

**Comment by Xanaxus** [comment]
I like it to be 50px but then restore button is overlapped by the prev pg button any idea how to fix it?

**Pull request merged**
